/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cppHRCC_cppHRCC */

#ifndef _Included_cppHRCC_cppHRCC
#define _Included_cppHRCC_cppHRCC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cppHRCC_cppHRCC
 * Method:    InitStatus
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_cppHRCC_cppHRCC_InitStatus
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     cppHRCC_cppHRCC
 * Method:    HRCCArrTask
 * Signature: (IDI)[I
 */
JNIEXPORT jintArray JNICALL Java_cppHRCC_cppHRCC_HRCCArrTask
  (JNIEnv *, jclass, jint, jdouble, jint);

/*
 * Class:     cppHRCC_cppHRCC
 * Method:    HRCCEndTask
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_cppHRCC_cppHRCC_HRCCEndTask
  (JNIEnv *, jclass, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
